# Generated by Django 6.0.5 on 2026-05-05 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено о')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я кур'єра")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено о')),
            ],
            options={
                'verbose_name': "Кур'єр",
                'verbose_name_plural': "Кур'єри",
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва страви')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Ціна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено о')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Страва',
                'verbose_name_plural': 'Страви',
            },
        ),
    ]
