# Generated by Django 6.0.5 on 2026-05-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Адреса доставки'),
        ),
    ]
